# Generated by Django 5.2.17 on 2026-10-03 21:24

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ParserTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bank", models.CharField(max_length=40)),
                ("name", models.CharField(max_length=80, unique=True)),
                (
                    "sender_ids",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=20),
                        help_text="SMS sender codes, e.g. HDFCBK",
                        size=None,
                    ),
                ),
                ("source", models.CharField(default="sms", max_length=10)),
                (
                    "txn_type",
                    models.CharField(
                        choices=[("debit", "Debit"), ("credit", "Credit")],
                        default="debit",
                        max_length=10,
                    ),
                ),
                (
                    "pattern",
                    models.TextField(
                        help_text="Regex with named groups: amount, payee, and optionally date, ref, account"
                    ),
                ),
                (
                    "flags",
                    models.CharField(
                        blank=True,
                        help_text="s = dot matches newline, i = ignore case",
                        max_length=4,
                    ),
                ),
                (
                    "date_format",
                    models.CharField(
                        blank=True, help_text="e.g. dd/MM/yy", max_length=20
                    ),
                ),
                (
                    "sample",
                    models.TextField(
                        blank=True,
                        help_text="A message this pattern must match (numbers changed)",
                    ),
                ),
                (
                    "priority",
                    models.PositiveSmallIntegerField(
                        default=100, help_text="Lower is tried first"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["priority", "id"],
            },
        ),
    ]
