# Generated by Django 5.2.17 on 2026-10-03 21:24

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("geo", "0001_initial"),
        ("merchants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("client_txn_id", models.UUIDField()),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("unknown", "Unknown"),
                            ("merchant", "Merchant"),
                            ("person", "Person"),
                        ],
                        default="unknown",
                        max_length=10,
                    ),
                ),
                ("occurred_on", models.DateField()),
                (
                    "day_part",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("morning", "Morning"),
                            ("afternoon", "Afternoon"),
                            ("evening", "Evening"),
                            ("night", "Night"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "amount_band",
                    models.CharField(
                        choices=[
                            ("lt_50", "Under ₹50"),
                            ("50_200", "₹50 to 200"),
                            ("200_500", "₹200 to 500"),
                            ("gt_500", "Above ₹500"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "sources",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("sms", "Sms"),
                                ("email", "Email"),
                                ("shortcut", "Shortcut"),
                                ("statement", "Statement"),
                            ],
                            max_length=10,
                        ),
                        default=list,
                        size=None,
                    ),
                ),
                ("ref_hash", models.CharField(blank=True, default="", max_length=64)),
                (
                    "location",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, geography=True, null=True, srid=4326
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "locality",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="geo.locality",
                    ),
                ),
                (
                    "merchant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transactions",
                        to="merchants.merchant",
                    ),
                ),
                (
                    "payee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transactions",
                        to="merchants.payee",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user", "-occurred_on"],
                        name="transaction_user_id_ac80f8_idx",
                    ),
                    models.Index(
                        fields=["user", "payee"], name="transaction_user_id_db668e_idx"
                    ),
                    models.Index(
                        condition=models.Q(("kind", "merchant")),
                        fields=["merchant", "user"],
                        name="txn_merchant_payer_idx",
                    ),
                    models.Index(
                        condition=models.Q(("kind", "merchant")),
                        fields=["locality", "merchant"],
                        name="txn_locality_merchant_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "client_txn_id"), name="uniq_user_client_txn"
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("ref_hash", ""), _negated=True),
                        fields=("user", "ref_hash"),
                        name="uniq_user_ref",
                    ),
                ],
            },
        ),
    ]
