# Generated by Django 5.2.17 on 2026-10-03 21:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Consent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("private_analytics", "C1 Private analytics"),
                            ("community_rankings", "C2 Community rankings"),
                            ("show_name", "C3 Show my name"),
                            ("location", "C4 Location"),
                            ("merchant_insights", "C5 Merchant insights"),
                        ],
                        max_length=32,
                    ),
                ),
                ("granted", models.BooleanField()),
                (
                    "notice_version",
                    models.CharField(
                        help_text="Version of the notice text the user saw",
                        max_length=20,
                    ),
                ),
                ("is_current", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        condition=models.Q(("granted", True), ("is_current", True)),
                        fields=["purpose", "user"],
                        name="consent_granted_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_current", True)),
                        fields=("user", "purpose"),
                        name="uniq_current_consent",
                    )
                ],
            },
        ),
    ]
