# Generated by Django 5.2.17 on 2026-10-04 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeocodeCell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('lng', models.DecimalField(decimal_places=6, max_digits=9)),
                ('status', models.CharField(choices=[('resolved', 'Resolved'), ('no_result', 'No Result')], max_length=10)),
                ('provider', models.CharField(max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('locality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cells', to='geo.locality')),
            ],
            options={
                'indexes': [models.Index(fields=['provider', 'status'], name='geo_geocode_provide_2fdfcc_idx')],
                'constraints': [models.UniqueConstraint(fields=('lat', 'lng'), name='uniq_geocode_cell')],
            },
        ),
    ]
