# Generated by Django 5.2.17 on 2026-10-03 21:24

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("merchants", "0001_initial"),
        ("transactions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TagWeight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "origin",
                    models.CharField(
                        choices=[
                            ("user", "User confirmed or entered"),
                            ("ai_own_history", "AI: this user's history at the shop"),
                            ("ai_crowd", "AI: other users' tags at the shop"),
                            ("ai_category", "AI: category, amount and time"),
                            ("ai_llm", "AI: LLM guess"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("weight", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=60)),
                ("slug", models.SlugField(max_length=70, unique=True)),
                ("is_category_default", models.BooleanField(default=False)),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False, help_text="False for items typed in by users"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="items",
                        to="merchants.category",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ItemAlias",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alias",
                    models.CharField(
                        help_text="Lower case", max_length=60, unique=True
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aliases",
                        to="tagging.item",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TransactionItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveSmallIntegerField(default=1)),
                (
                    "origin",
                    models.CharField(
                        choices=[
                            ("user", "User confirmed or entered"),
                            ("ai_own_history", "AI: this user's history at the shop"),
                            ("ai_crowd", "AI: other users' tags at the shop"),
                            ("ai_category", "AI: category, amount and time"),
                            ("ai_llm", "AI: LLM guess"),
                        ],
                        max_length=20,
                    ),
                ),
                ("confidence", models.FloatField(default=1.0)),
                (
                    "ai_origin",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("user", "User confirmed or entered"),
                            ("ai_own_history", "AI: this user's history at the shop"),
                            ("ai_crowd", "AI: other users' tags at the shop"),
                            ("ai_category", "AI: category, amount and time"),
                            ("ai_llm", "AI: LLM guess"),
                        ],
                        max_length=20,
                    ),
                ),
                ("rejected_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tags",
                        to="tagging.item",
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="transactions.transaction",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="item",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["name"], name="item_name_trgm", opclasses=["gin_trgm_ops"]
            ),
        ),
        migrations.AddConstraint(
            model_name="item",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_category_default", True)),
                fields=("category",),
                name="one_default_item_per_category",
            ),
        ),
        migrations.AddIndex(
            model_name="transactionitem",
            index=models.Index(
                fields=["item", "origin"], name="tagging_tra_item_id_f4ad83_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="transactionitem",
            constraint=models.UniqueConstraint(
                fields=("transaction", "item"), name="uniq_txn_item"
            ),
        ),
    ]
