# Generated by Django 5.2.17 on 2026-10-03 21:24

import django.contrib.gis.db.models.fields
from django.contrib.postgres.operations import CreateExtension, TrigramExtension
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        # Every other app's tables depend on this migration, so the extensions land first.
        CreateExtension("postgis"),
        TrigramExtension(),
        migrations.CreateModel(
            name="Locality",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("city", models.CharField(max_length=80)),
                ("state", models.CharField(blank=True, max_length=80)),
                (
                    "centre",
                    django.contrib.gis.db.models.fields.PointField(
                        geography=True, srid=4326
                    ),
                ),
                (
                    "boundary",
                    django.contrib.gis.db.models.fields.MultiPolygonField(
                        blank=True, geography=True, null=True, srid=4326
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "localities",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("name", "city"), name="uniq_locality_city"
                    )
                ],
            },
        ),
    ]
